name: toolchain
on:
  workflow_dispatch:

env:
  TAG_NAME: toolchain

jobs:
  toolchain:
    name: Toolchain
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false
      matrix:
        platform:
          - ssc338q_lite
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Build toolchain
        run: |
          GCC=$(make BOARD=${{matrix.platform}} toolname).tgz
          URL=https://github.com/${GITHUB_REPOSITORY}/releases/download/${TAG_NAME}/${GCC}
          echo ${URL}
          if ! wget -q --spider ${URL}; then
            make BOARD=${{matrix.platform}} toolchain
            SDK=$(find output/images -name *_sdk-buildroot.tar.gz)
            mv ${SDK} ${GCC}
            echo GCC=${GCC} >> ${GITHUB_ENV}
          fi

      - name: Upload toolchain
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{env.TAG_NAME}}
          make_latest: false
          files: ${{env.GCC}}
